# Generated by Django 5.0.3 on 2024-04-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_contenido_curso_imagen_estudiante_avatar_and_more'),
        ('cursos', '0011_curso_contenido_alter_curso_descripcion'),
    ]

    operations = [
    ]
