# Generated by Django 5.0.3 on 2024-04-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_merge_20240430_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(blank=True, default='estudiantes/fallback.png', upload_to='estudiantes'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='avatar',
            field=models.ImageField(blank=True, default='instructores/fallback.png', upload_to='instructores'),
        ),
    ]
